// Auto-generated by scripts/generate-release-notes-import.mjs — do not edit manually.
// Regenerated at build time and staged by `npm version`.

export interface ReleaseNoteVersion {
	version: string;
	content: string;
	date: string | null;
	isCurrent: boolean;
}

export const CURRENT_VERSION = "0.0.1";
export const RELEASE_NOTES_BUNDLE: ReleaseNoteVersion[] = [
];
